/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#131b2e",
        "primary-fixed": "#6ffbbe",
        "on-background": "#d3e4fe",
        "error-container": "#93000a",
        "surface-container": "#102034",
        "surface-tint": "#4edea3",
        "secondary-fixed": "#ffdadb",
        "surface-variant": "#26364a",
        "surface-container-highest": "#26364a",
        "surface-bright": "#2a3a4f",
        "inverse-on-surface": "#213145",
        "on-primary": "#003824",
        "inverse-primary": "#006c49",
        "on-error": "#690005",
        "primary-fixed-dim": "#4edea3",
        "on-surface-variant": "#bbcabf",
        "on-tertiary-container": "#31394d",
        "on-surface": "#d3e4fe",
        "tertiary": "#bec6e0",
        "outline": "#86948a",
        "surface-dim": "#031427",
        "surface-container-low": "#0b1c30",
        "on-tertiary-fixed-variant": "#3f465c",
        "tertiary-fixed": "#dae2fd",
        "on-error-container": "#ffdad6",
        "secondary-container": "#b50036",
        "surface": "#031427",
        "tertiary-fixed-dim": "#bec6e0",
        "error": "#ffb4ab",
        "on-tertiary": "#283044",
        "secondary-fixed-dim": "#ffb2b7",
        "on-secondary-fixed-variant": "#92002a",
        "primary": "#4edea3",
        "on-primary-container": "#00422b",
        "tertiary-container": "#9ba2bb",
        "primary-container": "#10b981",
        "on-primary-fixed-variant": "#005236",
        "inverse-surface": "#d3e4fe",
        "secondary": "#ffb2b7",
        "surface-container-high": "#1b2b3f",
        "on-secondary-fixed": "#40000d",
        "on-secondary-container": "#ffc2c4",
        "on-secondary": "#67001b",
        "surface-container-lowest": "#000f21",
        "on-primary-fixed": "#002113",
        "outline-variant": "#3c4a42",
        "background": "#031427",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "gutter": "1rem",
        "margin": "1.25rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-xl": "2rem",
        "margin-mobile": "1rem",
        "gutter-sm": "0.75rem",
        "space-md": "1rem",
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "numeric-balance": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "display-hero": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "numeric-balance": ["36px", { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.005em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
